### ISSUE TITLE
Error logs 1.9.4

### ISSUE THREAD

**Issue by Likkax** [Flynrod/FeatherSpawn#1]
I have a problem with FeatherSpawn:
`[Server thread/ERROR]: Could not pass event PlayerDeathEvent to FeatherSpawn v1.3.6
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.4.jar:git-Paper-773]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:409) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.EntityPlayer.die(EntityPlayer.java:419) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:108) [patched_1.9.4.jar:git-Paper-773]
    at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:41) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:98) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:23) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:151) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:471) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:381) [EssentialsX-2.0.1.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
    at be.flynrod.featherspawn.a.a(Unknown Source) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-773]
    ... 30 more`

**Comment by Flynrod** [comment]
When did you encounter this error?

**Comment by Likkax** [comment]
When players die
