### ISSUE TITLE
IllegalStateException: Asynchronous player tracker update!

### ISSUE THREAD

**Issue by Flynrod** [Flynrod/FeatherSpawn#14]
**FeatherSpawn version:** 1.9.82
**Error logs:**
```[19:51:29 WARN]: [FeatherSpawn] Plugin FeatherSpawn v1.9.82 generated an exception while executing task 2357
java.lang.IllegalStateException: Asynchronous player tracker update!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:327) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:216) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.EntityPlayer.G(EntityPlayer.java:1273) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.EntityPlayer.updateAbilities(EntityPlayer.java:1130) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setAllowFlight(CraftPlayer.java:1213) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at be.flynrod.obfuscation.j.a(Unknown Source) ~[?:?]
    at be.flynrod.obfuscation.j.X(Unknown Source) ~[?:?]
    at be.flynrod.obfuscation.u.run(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-596221b-9a1fc1e]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

**Comment by Flynrod** [comment]
Fixed with [1.9.9 update](https://www.spigotmc.org/resources/featherspawn.38865/)!
