### ISSUE TITLE
Bug: when i shoot in yourself i got a error

### ISSUE THREAD

**Issue by Sermax18** [Flynrod/FeatherSpawn#2]
version:1.5.4 server version:1.12.1 error:[12:54:17] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to FeatherSpawn v1.5.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:92) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:579) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:482) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:611) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1339) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:846) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:863) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:286) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1643) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1613) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [dpigot.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at a.b..c...d....e.....f......g.......h........i.........j..........k...........l............m.............n..............o...............p.e.a(Unknown Source) ~[?:?]
	at a.b..c...d....e.....f......g.......h........i.........j..........k...........l............m.............n..............o...............p.i.a(Unknown Source) ~[?:?]
	at a.b..c...d....e.....f......g.......h........i.........j..........k...........l............m.............n..............o...............p.i.a(Unknown Source) ~[?:?]
	at be.flynrod.featherspawn.a.c(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[dpigot.jar:git-Spigot-65e8124-963b19c]
	... 24 more

**Comment by Flynrod** [comment]
Thank you for your bug-report! I'm working on it.

**Comment by Sermax18** [comment]
and can i use it with https://www.spigotmc.org/resources/combatlogx.31689/?

**Comment by Flynrod** [comment]
FeatherSpawn work without this plugin ?

**Comment by Sermax18** [comment]
i haven't tried it yet

**Comment by Sermax18** [comment]
and my discord username:5678u
#9278

**Comment by Flynrod** [comment]
Sorry for this late response. Could you test with 1.5.7 version of FeatherSpawn ?
If you still get the error, could you send me a copy of your server privately (via PM on SpigotMC)?

**Comment by Sermax18** [comment]
i will send it in discord remember: my discord name: 5678u#9278
